### ISSUE TITLE
Unable to create project 

### ISSUE THREAD

**Issue by ambrinherz** [chasep255/Nexys4DDR-Ethernet#1]
Hello,

Thank you for a good example code. Unfortunately, while I was trying to create project with project.tcl I get critical warnings- "could not find top module in sources_1" "could not find top module in sim_1" etc.
I don't see sources_1, sim_1 folders inside the example folder or other folders. I was unable to create a project both with example and no example option.
Could you please update the project.tcl file, so I can generate a project. Appreciate your help in this regard.

Thank you,
Ambrin

**Comment by chasep255** [comment]
You need to run the create project.tcl make sure you are run it from the same directory as the script.  When I do it in example mode the script sets the top level module. In non-example mode it automatically detects top as eth_mac.  There is no sources_1 or sim_1 folder those are names of filesets.
